version: "3.9"
services:
  db:
    container_name: postgres-db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
  stc:
    container_name: stc-api
    image: stc:v1.0
    build:
      context: ./stc
    ports:
      - '8080:8080' 
    depends_on:
      - db
volumes:
  db:
    driver: local     